# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-04 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='categoria',
        ),
        migrations.AddField(
            model_name='album',
            name='categoria',
            field=models.ManyToManyField(null=True, to='app.Categoria'),
        ),
    ]
