# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-04 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160803_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='categoria',
            field=models.ManyToManyField(to='app.Categoria'),
        ),
    ]
